version: "3.8"
services:
  meme-api:
    image: 'ghcr.io/fergusdixon/${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    env_file:
      - .env
    build:
      context: ./meme-api
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "8888:80"
    volumes:
      - ./meme-api:/app
    command: /start-reload.sh

  meme-react-frontend:
    image: 'ghcr.io/fergusdixon/${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    ports:
      - "8080:80"
    depends_on:
      - meme-api
    build:
      context: ./meme-react-frontend
