version: "3.8"
services:
  meme-api:
    image: 'ghcr.io/fergusdixon/${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    environment:
      - PORT=8080
    env_file:
      - .env
    build:
      context: ./meme-api
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        x-aws-protocol: http

  meme-react-frontend:
    image: 'ghcr.io/fergusdixon/${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    ports:
      - 80:80
    depends_on:
      - meme-api
    build:
      context: ./meme-react-frontend

x-aws-cloudformation:
  Resources:
    MemeapiTCP8080TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/memes
        Matcher:
          HttpCode: 200
