version: "3.8"
services:
  meme-api:
    image: 'ghcr.io/fergusdixon/${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    environment:
      - PORT=8080
    env_file:
      - .env
    build:
      context: ./meme-api
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        x-aws-protocol: http
    deploy:
      replicas: 1
      update_config:
        order: start-first
      x-aws-autoscaling:
        min: 1
        max: 3
        cpu: 75
      resources:
        limits:
          cpus: '0.25'
          memory: 0.5Gb

  meme-react-frontend:
    image: 'ghcr.io/fergusdixon/${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    ports:
      - 80:80
    depends_on:
      - meme-api
    build:
      context: ./meme-react-frontend
    deploy:
      replicas: 1
      update_config:
        order: start-first
      x-aws-autoscaling:
        min: 1
        max: 3
        cpu: 75
      resources:
        limits:
          cpus: '0.25'
          memory: 0.5Gb

x-aws-cloudformation:
  Resources:
    MemeapiTCP8080TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/memes
        Matcher:
          HttpCode: 200
